---
title: "R Notebook"
output: html_notebook
---
```{r}
library(tidyverse)
```

```{r}
kcat <- 340 #per second
km <- 17000 #microMolar
enzyme_conc = 0.000095 #microMole/millilitre
t = 60 #time
alcohol_conc = 160000 #microMolar
moles_enzyme = (enzyme_conc * 100)/1000 
vmax = moles_enzyme * kcat * 4 #4 active sites
```

```{r}
#function to calculate velocity of enzyme reaction at given substrate concentration
velocity_calc <- function(s){
  v = (vmax * s)/(km + s)
  return(v)
}

#function to calculate new substrate concentration
substrateConc_calc <- function(s, v, t, rxntime){
  if (rxntime != 0){
    mole_alc = s * 0.003
    mole_alc = mole_alc - (v * t)
    s = mole_alc/0.003
    return(s)
  }
  else{
    return(s)
  }
}

#function to calculate remaining moles of substrate
molesSubstrate_calc <- function(s, v, t, rxntime){
  if (rxntime != 0){
    mole_alc = s * 0.003
    mole_alc = mole_alc - (v * t)
    return(mole_alc)
  }
  else{
    mole_alc = s * 0.003
    return(mole_alc)
  }
}

#function to calculate absorbance
absorbance_calc <- function(i, s){
  mole_product = i - s #moles of product
  conc_product = mole_product/0.003 #conctration of product microMolar
  conc_product = conc_product/1000000 #concentration of product in Molar
  abs = conc_product * 6220
  return(abs)
}
```


```{r}
a <- numeric()
b <- numeric()
rxntime = 0 #sets rxntime at 0
substrateConc = alcohol_conc #initial substrate concentration
initMolesSubs = alcohol_conc * 0.003 #initial Moles of substrate
timeInterval = 1
velocity = velocity_calc(substrateConc)
while(rxntime <= t){
  molesSubstrate = molesSubstrate_calc(substrateConc, velocity, timeInterval, rxntime) #moles of substrate remaining
  velocity = velocity_calc(substrateConc)
  absorbance = absorbance_calc(initMolesSubs, molesSubstrate)
  substrateConc = substrateConc_calc(substrateConc, velocity, timeInterval, rxntime)
  print(c(rxntime, velocity, molesSubstrate, substrateConc, absorbance))
  a <- c(a, absorbance)
  b <- c(b, rxntime)
  rxntime = rxntime + timeInterval
}
df <- data.frame(a, b)
colnames(df) <- c("substrate_depletion", "rxntime")
df
```
```{r}
substrateConc = alcohol_conc
velocity1 = velocity_calc(substrateConc)
rxntime = 0
abs2 = (((velocity1 / 0.003) / 1000000) * 6220)
abs = (((velocity1 * 60) / 0.003) / 1000000) * 6220
print(c(velocity1, abs, abs2))

abs3 = 0
while(rxntime <= t){
  print(abs3)
  abs3 = abs3 + abs2
  rxntime = rxntime + 1
  
}


```
```{r}
c <- numeric()
d <- numeric()
rxntime = 0 #sets rxntime at 0
substrateConc = alcohol_conc #initial substrate concentration
initMolesSubs = alcohol_conc * 0.003 #initial Moles of substrate
timeInterval = t
velocity = velocity_calc(substrateConc)
while(rxntime <= t){
  molesSubstrate = molesSubstrate_calc(substrateConc, velocity, timeInterval, rxntime) #moles of substrate remaining
  velocity = velocity_calc(substrateConc)
  absorbance = absorbance_calc(initMolesSubs, molesSubstrate)
  substrateConc = substrateConc_calc(substrateConc, velocity, timeInterval, rxntime)
  print(c(rxntime, velocity, molesSubstrate, substrateConc, absorbance))
  c <- c(c, absorbance)
  d <- c(d, rxntime)
  rxntime = rxntime + timeInterval
}
df2 <- data.frame(c, d)
colnames(df2) <- c("contant_substrate", "rxntime")
```

```{r}
test <- merge(df, df2, by = "rxntime", all = TRUE)
test1 <- test %>%
  pivot_longer(cols = !rxntime, names_to = "condition", values_to = "absorbance") %>%
  drop_na()
?pivot_longer
```
```{r}
test1 %>%
  group_by(condition) %>% 
  ggplot() +
  aes(x = rxntime, y = absorbance, group = condition, colour = condition) +
  geom_line()
  
```

